### ISSUE TITLE
How to initialize this program?

### ISSUE THREAD

**Issue by timsu92** [mphe/grayout.vim#14]
I'm installing it using vim-plugged by doing like this, omitting other plugins:
```vim
call plug#begin('~/.vim/plugged')
Plug 'mphe/grayout.vim'
call plug#end()
```
After this, I called `:PlugInstall` with success.

I appended the followings into ~/.vimrc :
```vim
" Run GrayoutUpdate when cursor stands still. This can cause lag in more complex files.
autocmd CursorHold,CursorHoldI * if &ft == 'c' || &ft == 'cpp' || &ft == 'objc' | exec 'GrayoutUpdate' | endif
" Set default compile flags.
" These are used, when no `compile_commands.json` or `.grayout.conf` file was found.
let g:grayout_default_args = [ '-x', 'c', '-std=c11' ]
" Set libclang searchpath. Leave empty for auto-detect.
let g:grayout_libclang_path = ''
" Enable to print debug messages inside vim.
let g:grayout_debug = 0
" Enable to write debug messages to `grayout.log`.
let g:grayout_debug_logfile = 0
```
Now, I open a .c file and move the cursor over a `#define`, and vim's command line shows `grayout.vim: ERROR: Not initialized`

My vim is 8.1 (2018 May 18, compiled Nov 08 2021 14:21:34),
Python 3.8.10,
clang version 10.0.0-4ubuntu1
Ubuntu 20.04.3 LTS

Could anyone tell me what I've lost or what I can try?

**Comment by mphe** [comment]
Please set `let g:grayout_debug_logfile = 1` and attach the `grayout.log` file.

**Comment by timsu92** [comment]
[grayout.log](https://github.com/mphe/grayout.vim/files/7642884/grayout.log)
I guess you are right as line 9 and line 22 both says it can't find `libclang.so`.
I installed clang through `sudo apt install clang`

**Comment by mphe** [comment]
Alright, so clang is installed, but it can't be found automatically.
Try to find out where clang was installed and set `g:grayout_libclang_path` respectively.

**Comment by timsu92** [comment]
After more searching the web, I installed `libclang-dev`and `libclang1` using apt, files' names start with libclang.so are:
- /usr/lib/llvm-10/lib/libclang.so
- /usr/lib/llvm-10/lib/libclang.so.1
- ~/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clang/lib/libclang.so
- ~/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clang/lib/libclang.so.13
- ~/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clang/lib/libclang.so.13.0.0

However, none of these work.

**Comment by mphe** [comment]
So you have tried `let g:grayout_libclang_path = '/usr/lib/llvm-10/lib/'`, etc. for all those paths and they all yield the same error?

**Comment by timsu92** [comment]
Oh! I thought that settings is used to point to the file!
Now it works well!
Thanks!

**Comment by mphe** [comment]
Glad I could help :+1: 
I updated the docs to better explain that setting.

**Comment by timsu92** [comment]
For people who needs it, here's how I had it done at that time in Ubuntu 20.04:
1. Install clang
   ```sh
   sudo apt install libclang1
   ```
2. move to the installation folder
   You need to change to a appropriate version of yours. For example:
   ```sh
   cd /usr/lib/llvm-14/lib
   ```
3. Alias the library
   ```sh
   sudo ln -s libclang.so.1 libclang.so
   ```
