### ISSUE TITLE
ARM Project not seeing #define

### ISSUE THREAD

**Issue by dale6998** [mphe/grayout.vim#2]
GrayoutUpdate seems to gray-out everything, even if the #define is in the same c file.

`#define HELLO

#ifdef HELLO
int x = 0;
#endif`

If I run `:GrayoutUpdate`, `int x = 0;` is grayed out even though `HELLO` was defined right above it.

This is my `.grayout.conf`:

`/usr/bin/arm-none-eabi-gcc -c -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DUSE_HAL_DRIVER -DSTM32F411xE -IDrivers/STM32F4xx_HAL_Driver/Inc -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F4xx/Include -IDrivers/CMSIS/Include -IInc -IInc -IBT 
`

**Comment by mphe** [comment]
You need to tell the compiler to stop after the preprocessing stage and to read the source from stdin.
It should work if you append "-E -" at the end of the command (-E only do preprocessing, - read from stdin).

**Comment by dale6998** [comment]
Ok, I've changed it as you've mentioned...I also noticed a typo in `-x -c` and changed that to `-x c`.
Here's the new command, but reloading the config file still doesn't fix the issue...If I read the docs correctly, I think I need to tell it what to include for preprocessing as well, correct?  And if so, I would need to add it `-I` directives.  Please let me know if I'm not understanding that right.

`/usr/bin/arm-none-eabi-gcc -x c -w -P -E -DUSE_HAL_DRIVER -DSTM32F411xE -IDrivers/STM32F4xx_HAL_Driver/Inc -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F4xx/Include -IDrivers/CMSIS/Include -IInc -IInc -IBT -
`

**Comment by mphe** [comment]
Hm, this looks correct.

I just tested it in a simple file with the above command and it worked perfectly fine.
Please try if this also doesn't work for you.
```c
int main(int argc, char *argv[])
{
#define HELLO
#ifdef HELLO
    int x = 0;
#else
    asdfasdfsdf;
#endif
    return 0;
}
```

Please try running `let grayout_debug = 1 `and post the output from `GrayoutUpdate`. It will show you if any compiler errors occurred and which regions it picked up that need to be grayed out.

In addition you can also try `let grayout_debug_compiler_inout = 1`. This will show you the input/output sent/received from the compiler. Depending on the file size and includes, this will be a lot of output, but it might give a clue, if `grayout_debug`, doesn't give any useful infos.



> I think I need to tell it what to include for preprocessing as well, correct?

Yes, you will need more or less the same parameters as if you would run the compiler manually in the command line. The plugin will invoke the compiler on the file to preprocess it and then checks the output to determine which lines to gray out.

**Comment by dale6998** [comment]
Thanks for the feedback, but it seems like all those options are pointing to one thing:  It can't find one of the first .h files.  However, the .h file in question (stm32f4xx_hal.h) is located in `Drivers/STM32F3xx_Hal_Driver/Inc/Legacy`, which looks like it's being included.

````
bufnr: 1
basesignid: 5074
numgrayouts: 0

Clearing existing grayouts...

Using cmd line: /usr/bin/arm-none-eabi-gcc -x c -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DUSE_HAL_DRIVER -DSTM32F411xE -IDrivers/STM32F4xx_HAL_Driver/Inc -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F4xx/Include -IDrivers/CMSIS/Include -IInc -IInc -IBT -w -P -E -

Compiler error:
 <stdin>:34:10: fatal error: stm32f4xx_hal.h: No such file or directory
compilation terminated.


Inactive blocks:
begin=226 end=238
begin=229 end=231
begin=273 end=283
begin=286 end=291
begin=293 end=342
begin=399 end=406
begin=401 end=403
begin=408 end=410
begin=429 end=431

Active blocks:

Applying new grayouts...
Creating grayout 5074 in line 227
Creating grayout 5075 in line 228
Creating grayout 5076 in line 229
Creating grayout 5077 in line 230
Creating grayout 5078 in line 231
Creating grayout 5079 in line 232
Creating grayout 5080 in line 233
Creating grayout 5081 in line 234
Creating grayout 5082 in line 235
Creating grayout 5083 in line 236
Creating grayout 5084 in line 237
Skipping nested block begin=229 end=231
Creating grayout 5085 in line 274
Creating grayout 5086 in line 275
Creating grayout 5087 in line 276
Creating grayout 5088 in line 277
Creating grayout 5089 in line 278
Creating grayout 5090 in line 279
Creating grayout 5091 in line 280
Creating grayout 5092 in line 281
Creating grayout 5093 in line 282
Creating grayout 5094 in line 287
Creating grayout 5095 in line 288
Creating grayout 5096 in line 289
Creating grayout 5097 in line 290
Creating grayout 5098 in line 294
Creating grayout 5099 in line 295
Creating grayout 5100 in line 296
Creating grayout 5101 in line 297
Creating grayout 5102 in line 298
Creating grayout 5103 in line 299
Creating grayout 5104 in line 300
Creating grayout 5105 in line 301
Creating grayout 5106 in line 302
Creating grayout 5107 in line 303
Creating grayout 5108 in line 304
Creating grayout 5109 in line 305
Creating grayout 5110 in line 306
Creating grayout 5111 in line 307
Creating grayout 5112 in line 308
(Re)Loading config file
Found config file /home/dale/PCBs/ESC/FW/.grayout.conf
-----------------------------------------------

(Re)Loading config file
Found config file /home/dale/PCBs/ESC/FW/.grayout.conf
-----------------------------------------------

bufnr: 1
basesignid: 5074
numgrayouts: 0

Clearing existing grayouts...

Using cmd line: /usr/bin/arm-none-eabi-gcc -x c -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DUSE_HAL_DRIVER -DSTM32F411xE -IDrivers/STM32F4xx_HAL_Driver/Inc -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F4xx/Include -IDrivers/CMSIS/Include -IInc -IInc -IBT -w -P -E -

Compiler error:
 <stdin>:34:10: fatal error: stm32f4xx_hal.h: No such file or directory
compilation terminated.


Inactive blocks:
begin=226 end=238
begin=229 end=231
begin=273 end=283
begin=286 end=291
begin=293 end=342
begin=399 end=406
begin=401 end=403
begin=408 end=410
begin=429 end=431

Active blocks:

Applying new grayouts...
Creating grayout 5074 in line 227
Creating grayout 5075 in line 228
Creating grayout 5076 in line 229
Creating grayout 5077 in line 230
Creating grayout 5078 in line 231
Creating grayout 5079 in line 232
Creating grayout 5080 in line 233
Creating grayout 5081 in line 234
Creating grayout 5082 in line 235
Creating grayout 5083 in line 236
Creating grayout 5084 in line 237
Skipping nested block begin=229 end=231
Creating grayout 5085 in line 274
Creating grayout 5086 in line 275
Creating grayout 5087 in line 276
Creating grayout 5088 in line 277
Creating grayout 5089 in line 278
Creating grayout 5090 in line 279
Creating grayout 5091 in line 280
Creating grayout 5092 in line 281
Creating grayout 5093 in line 282
Creating grayout 5094 in line 287
Creating grayout 5095 in line 288
Creating grayout 5096 in line 289
Creating grayout 5097 in line 290
Creating grayout 5098 in line 294
Creating grayout 5099 in line 295
Creating grayout 5100 in line 296
Creating grayout 5101 in line 297
Creating grayout 5102 in line 298
Creating grayout 5103 in line 299
Creating grayout 5104 in line 300
Creating grayout 5105 in line 301
Creating grayout 5106 in line 302
Creating grayout 5107 in line 303
Creating grayout 5108 in line 304
Creating grayout 5109 in line 305
Creating grayout 5110 in line 306
Creating grayout 5111 in line 307
Creating grayout 5112 in line 308
Creating grayout 5113 in line 309
```

**Comment by mphe** [comment]
I think I have an idea where the problem is.
The compiler will run in the current file's directory. So depending on where the file is located, the relative paths might not be correct.
Try using absolute paths in the command and see if it works then.

**Comment by dale6998** [comment]
nailed it...That fixed it.  I'll look around and see if I can make it run from where `.grayout.conf` is located so that relative paths will work...In the meantime, Thanks!

**Comment by mphe** [comment]
Glad I could help.
I just pushed a little fix, that introduces a new variable `g:grayout_workingdir`. Depending on its value it will use the current file's directory (0) or .grayout.conf's directory (1). If .grayout.conf can't be found, it will fall back to the current file.
