### ISSUE TITLE
errors on non C code

### ISSUE THREAD

**Issue by rwmitchell** [mphe/grayout.vim#4]
After recently updating both vim and plugins, I've started getting a bunch of errors related to Grayout when opening non C files:

Error detected while processing function <SNR>52_UpdateGrayout[13]..<SNR>52_RunPyScript:            

What is the proper way to limit the plugin to just .c.h files?

**Comment by mphe** [comment]
Technically there shouldn't be any errors even in non C files. Can you provide some more information including a minimal vimrc and an example file to reproduce the error?

GrayoutUpdate also does not get called automatically by default, so I guess you have an autocmd or similar in your config that runs GrayoutUpdate when you open a file. Autocmds have an option to specify a filetype.
You can also check the filetype in vim using `&ft`, e.g.
```vim
if &ft == 'c' || &ft == 'cpp'
    GrayoutUpdate
endif
```

**Comment by rwmitchell** [comment]
As usual, it is user error.

Given your comment, I changed this:

  `autocmd VimEnter * GrayoutUpdate`

to:

  `autocmd FileType C GrayoutUpdate`

and that seems to fix things.
