### ISSUE TITLE
Additional empty before line number after running GrayoutUpdate

### ISSUE THREAD

**Issue by kerol2r20** [mphe/grayout.vim#6]
Dear,
As title, after I running GrayoutUpdate, there are some additional empty symbol before line number.
Such like this.
![](https://i.imgur.com/6glwRqs.png)

How to fix it? or are these symbols with any other function?

Thanks.

**Comment by mphe** [comment]
This is vim's sign column. This plugin makes use of it to apply the gray highlight to the respective lines.

**Comment by kerol2r20** [comment]
Thanks for your response
