### ISSUE TITLE
Error parsing translation unit.

### ISSUE THREAD

**Issue by davy79** [mphe/grayout.vim#7]
Hi,

grayout.vim is currently not working for me and throws the following error:

`Error parsing translation unit.`

This is clang related, but I'm not sure what is causes it?

I'm running ubuntu 18.04.02 LTS and invoking grayout from neovim 
I have clang 6.0 and 9 installed... any specific version needed?

I remember a long time ago you had `grayout_debug_compiler_inout` but that doesn't seem to work anymore?

Any suggestions on how to aid in debugging this?

Thanks.

**Comment by mphe** [comment]
Hi,

I tested it on clang 9, not sure if it works with clang 6.

Please add `let g:grayout_debug_logfile = 1` to your vimrc and upload the `grayout.log` logfile.

`grayout_debug_compiler_inout` doesn't exist anymore because it is now completely clang based and the input is always your source file without any modifications.

**Comment by davy79** [comment]
Not much useful info in the logfile, but here it is...

I'm populating my own .grayout.conf file

```
Initialized          
Querying arguments for /home/jda/workspace/lib-mupet/src/lib_mupet.c
Searching /home/jda/workspace/lib-mupet/src/compile_commands.json
Searching /home/jda/workspace/lib-mupet/compile_commands.json
Searching /home/jda/workspace/compile_commands.json
Searching /home/jda/compile_commands.json
Searching /home/compile_commands.json
Searching /compile_commands.json
No config file found
Searching /home/jda/workspace/lib-mupet/src/.grayout.conf
Searching /home/jda/workspace/lib-mupet/.grayout.conf
Found config file /home/jda/workspace/lib-mupet/.grayout.conf
Using .grayout.conf
Compile flags: ['mlx16-gcc', '-x', 'c', '-w', '-P', '-E', '-nostdinc', '-I/home/jda/tools/mlx16-gcc/mlx16-gcc-3.0.39/mlx16/include', '-MMD', '-Iinc',
'-Iinfra/inc', '-Isrc', '-Itemplate', '-DGIT_HASH=0x3a63cc37UL', '-DFLASH=0', '-DFPLL=18000', '-DLIN_CLK_DIV=0', '-DCOMPILE_CONFIG_ID=13',
'-DUDS_CONFIGURATION_MEMORY', '-DUDS_CUSTOM_MEMORY', '-DUDS_SUPPORTED_SERVICES_MAX_NUM=10', '-DUDS_RECEIVE_BUFFER_MAX_LENGTH=180', '-DUDS_SEND_BUFFER_MAX_LENGTH=150', '-DUDS_SUPPORTED_SESSIONS_MAX_NUM=4', '-DUDS_SUPPORTED_SUBFUNCTIONS_MAX_NUM=2', '-DHAS_UDS_BOOTLOADER_DEFAULT_SERVICES_BMW', '-DLDT_HAS_CONSECUTIVE_FRA
MES=1', '-DMLX81118', '-DRELEASE_MAJOR=0', '-DRELEASE_MINOR=5', '-DRELEASE_REVISION=0', '-DFL_EE_HAS_WRITE_FUNC=1', '-DHAS_HW_EC_ADC', '-DPPM_EPM_ENABLED=1', '-DLIN_EPM_ENABLED=1', '-DLIN_EPM_BAUDRATE=19200', '-DHAS_EEPROM_WRITE_DATA', '-DFL_EE_HAS_WRITE_FUNC=1', '-DHAS_HW_NO_EN_AAIN', '-DBL_PHY_USE_PPM', '-DBL_PHY_U
SE_UDS_ON_LIN', '-DBL_AWD_TIMEOUT=16', '-DHAS_HW_FLASH_VCTAT_CTRL', '-DHAS_HW_FLASH_21', '-DHAS_HW_PPM_5V_TOLERANCE_WITH_INVERSION', '-DHAS_SW_PPM_BL_USE_ROM_ONLY', '-DHAS_SW_PPM_HAS_RAM_CODE_FRAME', '-DHAS_SW_STARTUP_RSTAT_SUPPORT', '-']
Error parsing translation unit.

```

**Comment by mphe** [comment]
Ah, I see. You need to remove the `-` at the end of your command. It is no longer necessary and produces errors instead. You also don't need this stuff `'-w', '-P', '-E', '-nostdinc'` anymore.

I rewrote this plugin from scratch and many things changed. I'd *strongly* suggest to read the docs again.

**Comment by davy79** [comment]
Ah I see...

I did read the docs... but completely missed the new conf syntax...
because I previously automated my conf file generation I assumed it to be OK... my bad...

I updated my conf file and now the plugin works again!!

Thanks for the great plugin... we often make heavy use of pre-processor switches and sometimes the code gets hard to read without grayout.

**Comment by mphe** [comment]
Glad I could help :+1:
