### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by rwmitchell** [mphe/grayout.vim#8]
Getting this error when running ':GrayoutUpdate' :
Error detected while processing function grayout#UpdateGrayout:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rwmitch1/.vim/bundle/grayout.vim/autoload/../python/grayout.py", line 52, in grayout
    tu = INDEX.parse(
AttributeError: 'NoneType' object has no attribute 'parse'

I have installed the ~latest python: python3 --version
Python 3.8.2

OSX: 10.14.6

MacVim is compiled with:
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm -lncurses  -lico
nv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl

:version shows I have both +python/dyn and +python3/dyn

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  4 2020 07:08:21)
macOS version
Included patches: 1-607

I've used the default grayout configuration arguments and just '-x c'.  I've attached the debug log showing both.

What do I have setup incorrectly?

[grayout.log](https://github.com/mphe/grayout.vim/files/4574351/grayout.log)

**Comment by mphe** [comment]
Hm, that is really strange.
Apparently the init function has not been called, even though it should, since the call is right after the python setup step, which got definitely executed, otherwise the `grayout()` function wouldn't even run.

What exactly were you doing?

Could you add a line `print("INITIALIZED")` in `autoload/grayout.vim` below line 19 (right below `grayout.init()` and before `EOF`)?
Then restart vim, try again and see if the message "INITIALIZED" shows up.
Also upload the log again after this.

**Comment by rwmitchell** [comment]
Wasn't really doing anything, except editing a .c file.  I used Grayout for a while, but then quit ~6 months ago because it appeared to have issues with something else I had installed.  Was missing the functionality, saw you had updated it and thought I'd try again.  I don't believe this is the same issue I had before, but it has been a while.

Anyway, I added:

import grayout
print("not yet INITIALIZED")
grayout.init()
print("INITIALIZED")

It prints out the first line, but not the second.  I removed my grayout.conf file and added enabling the debug options in .vimrc, here's the log:

[grayout.log](https://github.com/mphe/grayout.vim/files/4574952/grayout.log)

**Comment by rwmitchell** [comment]
earlier errors I had missed are:

Traceback (most recent call last):
  File "/Users/rwmitch1/.vim/bundle/grayout.vim/autoload/../python/clang/cindex.py", line 4229, in g
et_cindex_library
    library = cdll.LoadLibrary(self.get_filename())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 45
1, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 37
3, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/bin/libclang.dylib, 6): image not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/Users/rwmitch1/.vim/bundle/grayout.vim/autoload/../python/grayout.py", line 98, in init
    INDEX = cindex.Index.create()
  File "/Users/rwmitch1/.vim/bundle/grayout.vim/autoload/../python/clang/cindex.py", line 2701, in c
reate
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/Users/rwmitch1/.vim/bundle/grayout.vim/autoload/../python/clang/cindex.py", line 214, in __
get__
    value = self.wrapped(instance)
  File "/Users/rwmitch1/.vim/bundle/grayout.vim/autoload/../python/clang/cindex.py", line 4203, in l
ib
    lib = self.get_cindex_library()
  File "/Users/rwmitch1/.vim/bundle/grayout.vim/autoload/../python/clang/cindex.py", line 4234, in g
et_cindex_library
    raise LibclangError(msg)
clang.cindex.LibclangError: dlopen(/usr/bin/libclang.dylib, 6): image not found. To provide a path t
o libclang use Config.set_library_path() or Config.set_library_file().

**Comment by rwmitchell** [comment]
Added to .vimrc:

let g:grayout_libclang_path="/Library/Developer/CommandLineTools/usr/lib"

and that seems to have fixed it.

**Comment by mphe** [comment]
Alright, just came to the same conclusion, because that's the only way init() could abort midways.

I will add some checks and warnings if libclang could not be loaded.
