### ISSUE TITLE
Tags are not injected after an "#endif" in multi-line comments

### ISSUE THREAD

**Issue by huangda1982** [mphe/grayout.vim#9]
Thank you for your great work. It helps me a lot.

Source code like this (which is very common in those "lagacy" projects I am mentaining) will trigger the issue.
```C
/*#ifdef A
#ifdef B
// a tag is injected here
#endif
#endif*/
// no tags will be injected from here

#if D
// no tag injected here
#endif
```

It seems that "#endif*/" thing caused _parseblock() called directly from _parse() returned, and left the rest of source code unparsed.

I have a solution that works for me. I can not give a qualified pull request, since I am not familiar with python, and it is not well tested.
[grayout.py.txt](https://github.com/mphe/grayout.vim/files/4727250/grayout.py.txt)

And I guess this will trigger the same issue as well.
```C
char somestring[] = "\
#endif";
```

**Comment by mphe** [comment]
I rewrote this plugin from scratch some time ago.
You are still using the old version. The new version uses libclang and most certainly does not have this bug anymore.
Please read the readme on how to use it.

**Comment by huangda1982** [comment]
My fault. New version works great. Thank you.
